# Basic
title: 三行代码
subtitle: 技术博客
description: 欢迎访问我的博客
# 头像里面的标题
avatarTitle: 三行代码
# 头像里面的描述
avatarDesc: iOS/H5/安卓
url: "http://3code.info"

# 评论两种: 有言和 disqus
# Comment
comment:
    # disqus: hhha
     uyan: 2147278 

# Social
social:
    #weibo: 2344041987
    github: mythkiven
    #gsite: liliandreamworld
    #csdn: lilianforever
    twitter: Mr3code
    mail: 1282412855@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: d9432112fb859bf7276f8399641fb0c5

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-85978943-1  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
# 
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /blog/:year/:month/:title.html 

markdown: kramdown


kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge


# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: 

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 归档, description: archive, url: '/nav/archive'}   
    - {title: 分类, description: tags, url: '/nav/tags'}
    - {title: 留言, description: messages, url: '/nav/messages'}    
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"